'use server'

// Server Actions, not a Route Handler as docs/ESPN_INTEGRATION_PLAN.md §6 originally sketched --
// following the precedent set in app/admin/articles/[id]/edit/actions.ts, whose own comment
// explains why: every other admin write is a client component calling Supabase directly, and
// Server Actions are reserved for work that needs something only the server can do. Here that's
// calling the ESPN service with a secret token, not revalidatePath -- same reasoning, different
// server-only capability.
//
// Errors are returned as a string, not thrown, matching that same file's { error } convention --
// Next.js redacts thrown Server Action errors in production builds, which would hide the actually
// useful message ("ESPN credentials expired", a Postgres constraint violation, etc.).

import { createClient } from '@/lib/supabase/server'
import { isCommissioner } from '@/lib/supabase/roles'
import { fetchEspnTeams, type EspnTeam } from '@/lib/espn/client'
import type { Team } from '@/lib/types/poll'

type SupabaseServerClient = ReturnType<typeof createClient>

type ActionResult<T> = { data: T; error: null } | { data: null; error: string }

async function getCommissionerClient(): Promise<
  { supabase: SupabaseServerClient; error: null } | { supabase: null; error: string }
> {
  const supabase = createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user || !isCommissioner(user)) {
    return { supabase: null, error: 'Commissioner access required.' }
  }
  return { supabase, error: null }
}

function normalizeForMatch(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, '')
}

// ESPN's owner display name is frequently an autogenerated username, not a real name (see
// docs/ESPN_INTEGRATION_PLAN.md §2.4) -- so this is only a starting point for the commissioner's
// manual pairing below, never applied without confirmation. It suggests a pairing when exactly
// one still-unmatched ESPN team's owner name contains the DB team's owner first name; anything
// ambiguous or unmatched is left for manual selection in the UI.
function suggestPairing(dbOwnerName: string, candidates: EspnTeam[]): number | null {
  const needle = normalizeForMatch(dbOwnerName)
  if (!needle) return null

  const matches = candidates.filter((team) =>
    normalizeForMatch(team.owner_display_name ?? '').includes(needle)
  )
  return matches.length === 1 ? matches[0].espn_team_id : null
}

export interface TeamSyncPreviewRow {
  dbTeam: Team
  suggestedEspnTeamId: number | null
}

export interface TeamSyncPreview {
  rows: TeamSyncPreviewRow[]
  espnTeams: EspnTeam[]
  warnings: string[]
}

export async function previewEspnTeamSyncAction(
  seasonYear: number
): Promise<ActionResult<TeamSyncPreview>> {
  const auth = await getCommissionerClient()
  if (auth.supabase === null) return { data: null, error: auth.error }
  const { supabase } = auth

  try {
    const [espnResponse, dbResult] = await Promise.all([
      fetchEspnTeams(seasonYear),
      supabase.from('teams').select('*').eq('season_year', seasonYear).order('name'),
    ])

    if (dbResult.error) return { data: null, error: dbResult.error.message }

    const teams = (dbResult.data ?? []) as Team[]
    const espnTeamById = new Map(espnResponse.teams.map((team) => [team.espn_team_id, team]))
    const usedEspnIds = new Set<number>()

    // Rows already synced (from a previous sync) keep their existing pairing and are excluded
    // from the pool that unsynced rows can be suggested against.
    const rows: TeamSyncPreviewRow[] = teams.map((team) => {
      if (team.espn_team_id !== null && espnTeamById.has(team.espn_team_id)) {
        usedEspnIds.add(team.espn_team_id)
        return { dbTeam: team, suggestedEspnTeamId: team.espn_team_id }
      }
      return { dbTeam: team, suggestedEspnTeamId: null }
    })

    for (const row of rows) {
      if (row.suggestedEspnTeamId !== null) continue
      const candidates = espnResponse.teams.filter((team) => !usedEspnIds.has(team.espn_team_id))
      const suggestion = suggestPairing(row.dbTeam.owner_name, candidates)
      if (suggestion !== null) {
        row.suggestedEspnTeamId = suggestion
        usedEspnIds.add(suggestion)
      }
    }

    return {
      data: { rows, espnTeams: espnResponse.teams, warnings: espnResponse.warnings },
      error: null,
    }
  } catch (err) {
    return { data: null, error: err instanceof Error ? err.message : 'Failed to reach ESPN.' }
  }
}

export interface TeamSyncPairing {
  dbTeamId: string
  espnTeamId: number
  acceptOwnerName: boolean
}

export type TeamSyncPairingStatus = 'updated' | 'espn-team-missing' | 'no-matching-row'

export interface TeamSyncPairingResult {
  dbTeamId: string
  status: TeamSyncPairingStatus
}

export interface TeamSyncCommitResult {
  results: TeamSyncPairingResult[]
}

// Wire shape for sync_espn_teams (035) -- snake_case to match the jsonb keys the SQL function
// reads, deliberately distinct from Team (lib/types/poll.ts): this is a payload contract with the
// RPC boundary, not a partial update to that TS type.
interface SyncEspnTeamsPayloadItem {
  db_team_id: string
  name: string
  espn_team_id: number
  espn_owner_id: string | null
  owner_name: string | null
}

interface SyncEspnTeamsResultRow {
  db_team_id: string
  updated: boolean
}

export async function commitEspnTeamSyncAction(
  seasonYear: number,
  pairings: TeamSyncPairing[]
): Promise<ActionResult<TeamSyncCommitResult>> {
  const auth = await getCommissionerClient()
  if (auth.supabase === null) return { data: null, error: auth.error }
  const { supabase } = auth

  if (pairings.length === 0) {
    return { data: { results: [] }, error: null }
  }

  try {
    // Re-fetch rather than trusting the team name/owner data the client already has -- the
    // client only needs to tell us which pairing it chose, not what ESPN's data says. This also
    // means only a genuine re-check of ESPN, not stale data from whenever preview last ran.
    const espnResponse = await fetchEspnTeams(seasonYear)
    const espnTeamById = new Map(espnResponse.teams.map((team) => [team.espn_team_id, team]))

    const results: TeamSyncPairingResult[] = []
    const payload: SyncEspnTeamsPayloadItem[] = []

    for (const pairing of pairings) {
      const espnTeam = espnTeamById.get(pairing.espnTeamId)
      // ESPN team vanished between preview and commit (renamed/removed mid-season) -- report it
      // rather than silently dropping it or writing stale data.
      if (!espnTeam) {
        results.push({ dbTeamId: pairing.dbTeamId, status: 'espn-team-missing' })
        continue
      }

      payload.push({
        db_team_id: pairing.dbTeamId,
        name: espnTeam.name,
        espn_team_id: espnTeam.espn_team_id,
        espn_owner_id: espnTeam.espn_owner_id,
        owner_name: pairing.acceptOwnerName ? espnTeam.owner_display_name : null,
      })
    }

    if (payload.length > 0) {
      // sync_espn_teams (035) applies the whole batch in one transaction -- a unique-violation on
      // any single row (e.g. two pairings claiming the same espn_team_id) rolls back the entire
      // batch rather than leaving some teams already re-pointed and others not.
      const { data, error } = await supabase.rpc('sync_espn_teams', {
        p_season_year: seasonYear,
        p_pairings: payload,
      })
      if (error) return { data: null, error: error.message }

      const updatedByDbTeamId = new Map(
        (data as SyncEspnTeamsResultRow[]).map((row) => [row.db_team_id, row.updated])
      )
      for (const item of payload) {
        results.push({
          dbTeamId: item.db_team_id,
          status: updatedByDbTeamId.get(item.db_team_id) ? 'updated' : 'no-matching-row',
        })
      }
    }

    return { data: { results }, error: null }
  } catch (err) {
    return { data: null, error: err instanceof Error ? err.message : 'Failed to sync from ESPN.' }
  }
}
